version: "3"
services:
  web:
    image: apptest:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4200:3000"
    networks:
      - webnet
    depends_on:
       - db 
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - webnet
networks:
  webnet:
volumes:
  mongodata: